build:debian: &build-debian
  name: Build
  command: |
    set -x;
    apt-get -yqq update;
    apt-get -yqq install \
        dpkg-dev \
        devscripts;
    pushd $(mktemp -d -p .);
    tar -xf ../gwosc-*.tar.gz --strip-components=1;
    # install build dependencies
    mk-build-deps --tool "apt-get -y" --install --remove;
    # build binary package
    dpkg-buildpackage -us -uc -b;
    # mv and install
    popd;
    rm -rf tmp*;
    dpkg --install python*-gwosc*.deb;

build:centos: &build-centos
  name: Build
  command: |
    set -x;
    yum -y -q update;
    yum -y -q install \
        yum-utils \
        rpm-build \
        python34 \
        python3-rpm-macros;
    # hack version number
    tar -xf gwosc-*.tar.gz;
    rm -rf gwosc-*.tar.gz;
    _version=$(grep "define version" gwosc-*/gwosc.spec | awk '{print $3}');
    mv gwosc-* gwosc-${_version};
    tar -zcf gwosc-${_version}.tar.gz gwosc-${_version};
    rm -rf gwosc-${_version}/;
    # build src rpm
    SRC_RPM=$(rpmbuild -ts gwosc*.tar.gz | cut -d\  -f2);
    # install build dependencies
    yum-builddep -y -q ${SRC_RPM};
    # build binary rpm(s)
    rpmbuild --quiet --define "_rpmdir $(pwd)" --rebuild ${SRC_RPM};
    # mv and install
    mv noarch/*.rpm .;
    rm -rf noarch;
    yum -y -q --nogpgcheck localinstall *.rpm;

prepare-test:debian: &prep-test-debian
  name: Prepare tests
  command: |
    set -x;
    apt-get -yqq install \
        python-pip python3-pip \
        python-pytest python3-pytest \
        python-pytest-cov python3-pytest-cov;

prepare-test:centos: &prep-test-centos
  name: Prepare tests
  command: |
    set -x;
    yum -y -q install \
        python2-pip python34-pip \
        pytest python34-pytest \
        python2-pytest-cov python34-pytest-cov;

test: &test
  name: Test
  command: |
    set -x;
    python${PYTHON_VERSION} -m pip install pytest pytest-cov;
    python${PYTHON_VERSION} -m pytest --pyargs gwosc --cov=gwosc;


debian: &debian
  steps:
    - attach_workspace:
        at: .
    - run: *build-debian
    - run: *prep-test-debian
    - run: *test
    - store_artifacts:
        path: "*.deb"

centos: &centos
  steps:
    - attach_workspace:
        at: .
    - run: *build-centos
    - run: *prep-test-centos
    - run: *test
    - store_artifacts:
        path: "*.rpm"

version: 2
jobs:
  sdist:
    docker:
      - image: python
    steps:
      - checkout
      - run: python setup.py --quiet sdist --dist-dir .
      - persist_to_workspace:
          root: .
          paths:
            - "gwosc-*.tar.gz"

  debian:stretch:2.7:
    <<: *debian
    docker:
      - image: ligo/base:stretch
    environment:
      PYTHON_VERSION: "2.7"

  debian:stretch:3.5:
    <<: *debian
    docker:
      - image: ligo/base:stretch
    environment:
      PYTHON_VERSION: "3.5"

  el7:2.7:
    <<: *centos
    docker:
      - image: ligo/base:el7
    environment:
      PYTHON_VERSION: "2.7"

  el7:3.4:
    <<: *centos
    docker:
      - image: ligo/base:el7
    environment:
      PYTHON_VERSION: "3.4"

workflows:
  version: 2
  build_and_test:
    jobs:
      - sdist
      - debian:stretch:2.7:
          requires:
            - sdist
      - debian:stretch:3.5:
          requires:
            - sdist
      - el7:2.7:
          requires:
            - sdist
      - el7:3.4:
          requires:
            - sdist
